apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-config
  namespace: crypto-analytics
data:
  KAFKA_BROKERS: kafka:9092
  ES_URL: http://elasticsearch:9200
  REDIS_ADDR: redis:6379
  CHAINS: ethereum,cosmos,solana
  CONFIRMATIONS: "12"
