apiVersion: v1
kind: Secret
metadata:
  name: crypto-secrets
  namespace: crypto-analytics
type: Opaque
stringData:
  PG_DSN: postgres://postgres:postgres@timescaledb:5432/crypto_analytics?sslmode=disable
  JWT_SECRET: change-me
  ETHEREUM_RPC_URL: https://ethereum-rpc.publicnode.com
  COSMOS_RPC_URL: https://rpc.cosmos.network:443
  SOLANA_RPC_URL: https://api.mainnet-beta.solana.com
