global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: crypto-dummy
    metrics_path: /metrics
    static_configs:
      - targets: ["crypto-dummy-exporter-force:9109"]

  - job_name: crypto-dummy-localhost
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9109"]
