global:
  scrape_interval: 15s
scrape_configs:
  - job_name: ingestor
    static_configs:
      - targets: ['ingestor:8081']
  - job_name: indexer
    static_configs:
      - targets: ['indexer:8082']
  - job_name: api
    static_configs:
      - targets: ['api:8080']
